mode: restart
max_exceeded: silent

variables:
  enable_entity: !input enable_entity

triggers:
  - trigger: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
    id: activate

  - trigger: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for: !input deactivate_delay
    id: deactivate

  - trigger: state
    entity_id: !input controlled_light
    from:
      - "off"
      - "on"
    to:
      - "off"
      - "on"
    id: manual

conditions:
  - condition: template
    value_template: >
      {{ enable_entity == '' or is_state(enable_entity, 'on') }}
